services:
  webserv:
    container_name: webserv
    build: ./
    ports:
      - "90:90"
      - "80:80"
      - "81:81"
    volumes: 
      - webserv_volume:/app
    tty: true
    stdin_open: true


volumes:
  webserv_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "${PWD}/"

