name: Build and Run Webserv

on:
    push:
        branches:
            - '**'

jobs:
    build-and-run:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install build dependencies
                run: sudo apt-get update && sudo apt-get install -y build-essential

            - name: Build with Makefile
                run: make

            - name: Run webserv
                run: ./webserv